# Generated by Django 5.2.3 on 2025-07-05 12:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SleepRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleep_date_time', models.DateTimeField()),
                ('sleep_rem_duration', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1440)])),
                ('has_rem', models.BooleanField(default=False)),
                ('min_hr', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('device_bedtime', models.DateTimeField(blank=True, null=True)),
                ('sleep_deep_duration', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1440)])),
                ('wake_up_time', models.DateTimeField(blank=True, null=True)),
                ('bedtime', models.DateTimeField(blank=True, null=True)),
                ('awake_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duration', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_hr', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sleep_awake_duration', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('avg_hr', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sleep_light_duration', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1440)])),
                ('device_wake_up_time', models.DateTimeField(blank=True, null=True)),
                ('total_time_bed', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1440)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'sleep_date_time')},
            },
        ),
        migrations.CreateModel(
            name='NightHeartRateEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('bpm', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)])),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='night_hr_entries', to='sleep_tracking_app.sleeprecord')),
            ],
        ),
        migrations.CreateModel(
            name='SleepSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('state', models.PositiveSmallIntegerField(choices=[(2, 'Light'), (3, 'Deep'), (4, 'REM'), (5, 'Awake')])),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='sleep_tracking_app.sleeprecord')),
            ],
        ),
        migrations.CreateModel(
            name='SleepStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latency_minutes', models.FloatField()),
                ('sleep_efficiency', models.FloatField()),
                ('sleep_phases', models.JSONField()),
                ('sleep_fragmentation_index', models.FloatField()),
                ('sleep_calories_burned', models.FloatField()),
                ('sleep_duration', models.PositiveSmallIntegerField()),
                ('sleep_quality', models.FloatField()),
                ('health_impact', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('calories_burned', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(10)])),
                ('gender', models.PositiveSmallIntegerField(choices=[(0, 'Женский'), (1, 'Мужской')], default=0)),
                ('height', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(10)])),
                ('active', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
