# Generated by Django 5.2.3 on 2025-08-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleep_tracking_app', '0002_alter_sleepstatistics_calories_burned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleepstatistics',
            name='date',
            field=models.DateField(),
        ),
    ]
