# Generated by Django 5.2.3 on 2025-08-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleep_tracking_app', '0005_sleepstatistics_is_recommended'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sleepstatistics',
            name='is_recommended',
        ),
        migrations.AddField(
            model_name='sleepstatistics',
            name='recommended',
            field=models.TextField(blank=True, null=True),
        ),
    ]
