# Generated by Django 5.2.8 on 2025-11-30 11:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sleep_tracking_app", "0006_remove_sleepstatistics_is_recommended_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdata",
            name="height",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(40),
                    django.core.validators.MaxValueValidator(270),
                ]
            ),
        ),
    ]
