# Generated by Django 5.2.3 on 2025-08-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleep_tracking_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleepstatistics',
            name='calories_burned',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sleepstatistics',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='sleepstatistics',
            name='health_impact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sleepstatistics',
            name='latency_minutes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sleepstatistics',
            name='sleep_calories_burned',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sleepstatistics',
            name='sleep_duration',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sleepstatistics',
            name='sleep_efficiency',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sleepstatistics',
            name='sleep_fragmentation_index',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sleepstatistics',
            name='sleep_phases',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sleepstatistics',
            name='sleep_quality',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
