# Generated by Django 5.2.3 on 2025-08-16 16:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleep_tracking_app', '0003_alter_sleepstatistics_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleeprecord',
            name='sleep_date_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='sleepstatistics',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='sleeprecord',
            index=models.Index(fields=['user', 'sleep_date_time'], name='sleep_track_user_id_da25e8_idx'),
        ),
        migrations.AddIndex(
            model_name='sleepstatistics',
            index=models.Index(fields=['user', 'date'], name='sleep_track_user_id_7cbfa7_idx'),
        ),
    ]
