# Generated by Django 5.2.3 on 2025-08-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleep_tracking_app', '0004_alter_sleeprecord_sleep_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleepstatistics',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
    ]
